export const GET_LIST_RATED_MOVIE = "GET_LIST_RATED_MOVIE";
export const GET_LIST_RATED_TV = "GET_LIST_RATED_TV";
export const GET_LIST_FAVORITE_MOVIE = "GET_LIST_FAVORITE_MOVIE";

export const GET_CREATED_LIST = "GET_CREATED_LIST";
export const GET_DETAILS_LIST = "GET_DETAILS_LIST";
export const GET_LIST_SEARCH = "GET_LIST_SEARCH";

export const CREATE_NEW_LIST = "CREATE_NEW_LIST";

export const DETELE_LIST_SEARCH = "DELE_LIST_SEARCH";
