export const GET_LIST_RATED_MOVIE = "GET_LIST_RATED_MOVIE";
export const GET_LIST_RATED_TV = "GET_LIST_RATED_TV";
export const GET_LIST_FAVORITE_MOVIE = "GET_LIST_FAVORITE_MOVIE";

export const GET_CREATED_LIST = "GET_CREATED_LIST";
