export const GET_PHOTOS_MOVIE = "GET_PHOTOS_MOVIE";
export const GET_CREDIT_MOVIE = "GET_CREDIT";
export const GET_SIMILAR_MOVIE = "GET_SIMILAR_MOVIE";
export const GET_REVIEWS_MOVIE = "GET_REVIEWS_MOVIE";
export const GET_BANNER_MOVIE = "GET_BANNER_MOVIE";

export const GET_PHOTOS_TV_SHOW = "GET_PHOTOS_TV_SHOW";
export const GET_CREDIT_TV_SHOW = "GET_CREDIT";
export const GET_SIMILAR_TV_SHOW = "GET_SIMILAR_TV_SHOW";
export const GET_REVIEWS_TV_SHOW = "GET_REVIEWS_TV_SHOW";
export const GET_BANNER_TV_SHOW = "GET_BANNER_TV_SHOW";
