export const GET_LIST_MOVIE_POPULAR = "GET_LIST_MOVIE_POPULAR";
export const GET_LIST_MOVIE_TOP_RATED = "GET_LIST_MOVIE_TOP_RATED";
export const GET_LIST_MOVIE_NOW_PLAYING = "GET_LIST_MOVIE_NOW_PLAYING";
export const GET_LIST_MOVIE_UP_COMING = "GET_LIST_MOVIE_UP_COMING";
export const GET_TRAILER_MOVIE_POPULAR = "GET_TRAILER_MOVIE_POPULAR";

export const GET_MOVIE_LIST = "GET_MOVIE_LIST";

export const GET_GENRES_MOVIE_LIST = "GET_GENRES_MOVIE_LIST";

export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_TV_SHOW = "GET_TV_SHOW";
